---

- name: stop-and-mask default tor instance
  become: yes
  systemd:
    name: 'tor@default'
    state: 'stopped'
    enabled: False
    masked: True
  when: ansible_pkg_mgr == 'apt'

- name: restart apparmor
  become: yes
  service: name=apparmor state=restarted

- name: systemctl daemon-reload
  become: yes
  systemd:
    daemon_reload: True

- name: re-gather facts
  setup:

- name: disable default tor instance FreeBSD
  become: yes
  lineinfile:
    dest: /etc/rc.conf
    line: "tor_disable_default_instance=\"YES\""
    create: yes
  when: ansible_system == 'FreeBSD'

# TODO: this restarts all instances on a FreeBSD host even if just one torrc changed
- name: restart tor instances (FreeBSD)
  become: yes
  service:
    name: tor
    state: restarted
  when: ansible_system == 'FreeBSD'

- name: restart tor instances (Linux)
  become: yes
  service:
    name: "tor@{{ item.item.0.ipv4 }}_{{ item.item.1.orport }}.service"
    state: restarted
  with_items: "{{ tor_instances_tmp.results }}"
  when: item.changed and ansible_system == 'Linux'

- name: restart tor instances (OpenBSD)
  become: yes
  service:
    name: "tor{{ item.item.0.ipv4|replace('.','_') }}_{{ item.item.1.orport }}"
    state: restarted
  with_items: "{{ tor_instances_tmp.results }}"
  when: item.changed and ansible_system == 'OpenBSD'
  tags:
    - reconfigure
